package com.earthtrip.expense.domain;
import java.time.Instant;import java.util.*;
public final class Expense{
 private final UUID id;private final UUID tripId;private String title;private String categoryCode;private long amountMinor;private String currency;private Instant occurredAt;private Map<UUID,Long> payers;private Map<UUID,Long> shares;private String visibility;private String status;private String note;private final UUID createdBy;private UUID updatedBy;private final Instant createdAt;private Instant updatedAt;private Instant deletedAt;private final long version;
 private Expense(UUID id,UUID trip,String title,String category,long amount,String currency,Instant occurred,Map<UUID,Long> payers,Map<UUID,Long> shares,String visibility,String status,String note,UUID createdBy,UUID updatedBy,Instant created,Instant updated,Instant deleted,long version){this.id=id;tripId=trip;this.createdBy=createdBy;createdAt=created;this.version=version;apply(title,category,amount,currency,occurred,payers,shares,visibility,status,note,updatedBy,updated);deletedAt=deleted;}
 public static Expense create(UUID id,UUID trip,String title,String category,long amount,String currency,Instant occurred,Map<UUID,Long> payers,Map<UUID,Long> shares,String visibility,String note,UUID actor,Instant now){return new Expense(id,trip,title,category,amount,currency,occurred,payers,shares,visibility,"RECORDED",note,actor,actor,now,now,null,0);}
 public static Expense restore(UUID id,UUID trip,String title,String category,long amount,String currency,Instant occurred,Map<UUID,Long> payers,Map<UUID,Long> shares,String visibility,String status,String note,UUID createdBy,UUID updatedBy,Instant created,Instant updated,Instant deleted,long version){return new Expense(id,trip,title,category,amount,currency,occurred,payers,shares,visibility,status,note,createdBy,updatedBy,created,updated,deleted,version);}
 public void update(String title,String category,Long amount,String currency,Instant occurred,Map<UUID,Long> payers,Map<UUID,Long> shares,String visibility,String status,String note,UUID actor,Instant now){apply(title==null?this.title:title,category==null?categoryCode:category,amount==null?amountMinor:amount,currency==null?this.currency:currency,occurred==null?occurredAt:occurred,payers==null?this.payers:payers,shares==null?this.shares:shares,visibility==null?this.visibility:visibility,status==null?this.status:status,note==null?this.note:note,actor,now);}
 public void markSplit(UUID actor,Instant now){status="SPLIT";updatedBy=actor;updatedAt=now;}public void delete(UUID actor,Instant now){deletedAt=now;updatedBy=actor;updatedAt=now;}
 private void apply(String title,String category,long amount,String currency,Instant occurred,Map<UUID,Long> payers,Map<UUID,Long> shares,String visibility,String status,String note,UUID actor,Instant now){if(title==null||title.isBlank()||title.strip().length()>200)throw new IllegalArgumentException("지출 이름을 확인해 주세요.");if(amount<=0)throw new IllegalArgumentException("지출 금액은 0보다 커야 합니다.");this.title=title.strip();categoryCode=text(category,80).toUpperCase(Locale.ROOT);this.currency=java.util.Currency.getInstance(currency.strip().toUpperCase(Locale.ROOT)).getCurrencyCode();amountMinor=amount;occurredAt=Objects.requireNonNull(occurred);this.payers=validatedAmounts(payers,amount,"결제자 기여액");this.shares=validatedAmounts(shares,amount,"참여자 부담액");this.visibility=text(visibility,20).toUpperCase(Locale.ROOT);if(!Set.of("PRIVATE","PARTICIPANTS","TRIP").contains(this.visibility))throw new IllegalArgumentException("지원하지 않는 공개 범위입니다.");this.status=text(status,30).toUpperCase(Locale.ROOT);this.note=note==null||note.isBlank()?null:note.strip();if(this.note!=null&&this.note.length()>5000)throw new IllegalArgumentException("메모가 너무 깁니다.");updatedBy=actor;updatedAt=now;}
 private static Map<UUID,Long> validatedAmounts(Map<UUID,Long> values,long total,String label){if(values==null||values.isEmpty())throw new IllegalArgumentException(label+"이 필요합니다.");if(values.values().stream().anyMatch(v->v==null||v<0)||values.values().stream().mapToLong(Long::longValue).sum()!=total)throw new IllegalArgumentException(label+" 합계가 지출 총액과 일치해야 합니다.");return Map.copyOf(values);}private static String text(String v,int max){if(v==null||v.isBlank()||v.strip().length()>max)throw new IllegalArgumentException("필수 값을 확인해 주세요.");return v.strip();}
 public UUID id(){return id;}public UUID tripId(){return tripId;}public String title(){return title;}public String categoryCode(){return categoryCode;}public long amountMinor(){return amountMinor;}public String currency(){return currency;}public Instant occurredAt(){return occurredAt;}public Map<UUID,Long> payers(){return payers;}public Map<UUID,Long> shares(){return shares;}public String visibility(){return visibility;}public String status(){return status;}public String note(){return note;}public UUID createdBy(){return createdBy;}public UUID updatedBy(){return updatedBy;}public Instant createdAt(){return createdAt;}public Instant updatedAt(){return updatedAt;}public Instant deletedAt(){return deletedAt;}public long version(){return version;}
}
